### ISSUE TITLE
Steam Launch Options Ignored

### ISSUE THREAD

**Issue by Hadi77KSA** [InvoxiPlayGames/BO3MacFix#1]
Hello! I noticed that, when the fix is installed, the Steam launch options entries set for the game get ignored. The following is an example of a set of entries that work when the fix is not installed:
`+set fs_game usermaps +developer 0 +logfile 2`
However, with the fix installed, none of the entries gets registered. There are likely other entries that work, but I don’t know them unfortunately.

**Comment by InvoxiPlayGames** [comment]
Oh! I had no idea people used launch arguments I'll be honest, I'll have to add support to the AppBundleExe launcher. For now, as a workaround, you can launch the game via the Terminal:

`cd "/path/to/steamapps/common/Call of Duty Black Ops 3"`
`export SteamAppId=311210`
`export BO3MACFIX_NETWORKPASSWORD=your_network_password` (if using a network password)
`DYLD_INSERT_LIBRARIES=./BO3MacFix/BO3MacFix.dylib ./CoDBlkOps3.app/Contents/MacOS/CoDBlkOps3_Exe +set fs_game usermaps +developer 0 +logfile 2`

This should work? It's not very convinient though.

**Comment by Hadi77KSA** [comment]
Seems to have worked! Hopefully symbols in the parameters won’t bring up issues if taken from Steam unlike when writing them into the Terminal (examples: `!test` or `[test]` or whatever other macOS shenanigans there are). 😅
Anyway, keep up the good work and I hope you the best of luck!

**Comment by Hadi77KSA** [comment]
Idk how to handle GitHub issues. I guess I'll close it when the feature is implemented or confirmed not to be supported.

**Comment by InvoxiPlayGames** [comment]
I've just updated the launcher binary to add support for hopefully specifying launch arguments. If you can, could you build the launcher and try it out now?

To build the launcher, in a Terminal:
```
git clone https://github.com/InvoxiPlayGames/BO3MacFix.git
cd BO3MacFix
cd launcher
make
cp AppBundleExe "/path/to/steamapps/common/Call of Duty Black Ops 3/CoDBlkOps3.app/Contents/MacOS/AppBundleExe"
```

(I haven't actually had the time or patience to test it myself, I don't like replacing AppBundleExe anymore because of Gatekeeper...)

**Comment by Hadi77KSA** [comment]
Working good from my brief testing. Thank you!
![image](https://github.com/user-attachments/assets/d18b4e08-e912-4ed7-a480-06a483cd37ad)
![image](https://github.com/user-attachments/assets/7e4890cc-12db-4784-9806-5f9695a8aac8)
