### ISSUE TITLE
why ntfs is not supported 

### ISSUE THREAD

**Issue by abdelaziz-mahdy** [InvoxiPlayGames/BO3MacFix#10]
i downloaded the game to ntfs drive, so this is why i am asking why its not supported and if there is anything i can do to support it let  me know

if its a problem with write permission i am using ntfs for mac, so i can write to the drive

**Comment by InvoxiPlayGames** [comment]
NTFS tends to be very hit-or-miss with file permissions, and it can really confuse Wine which is needed for the custom map conversion to work.

You could try it, it might work, but I wasn't able to get it to work.

**Comment by abdelaziz-mahdy** [comment]
well i used another drive which has the supported, format so thank you for explaining the problem
