### ISSUE TITLE
Multiplayer doesn't work with Windows players (and vice versa)

### ISSUE THREAD

**Issue by goldenstuff** [InvoxiPlayGames/BO3MacFix#2]
Hi! This has been a lifesaver for us for Zombies at least, as it all works perfectly (except for AAE), but when we've tried multiplayer custom games, the Windows users seem to stay stuck loading before losing connection to host, and the Mac user loads in just fine. This also happens the other way around so the Windows users can load in but the Mac user won't. Let me know if there's a workaround or fix for this. Thank you!

**Comment by InvoxiPlayGames** [comment]
Thanks for the report! I didn't actually test multiplayer when developing this.

We've managed to figure it out, the next update to BO3MacFix will have a proper fix built-in but for now as a workaround:

1. Open the Steam console on your Mac: steam://open/console
2. Run `download_depot 311210 408837 221910284780888343`
3. After it's done downloading (~1.2GB), go to the folder it gives to you in the console in Finder, then copy `mp_patch.ff` from the zone folder inside there.
    * As an alternative to downloading a gig worth of game files, get someone on Windows to send you this file from their BO3 download.
5. Go to your BO3 install folder, right click on the BO3 app and click "Show package contents", go to Contents/Assets/zone and paste `mp_patch.ff` into there, overwriting the original.

**Comment by goldenstuff** [comment]
This works. Thank you!
